import wx

ID_TOGGLE_OBJECTS = wx.ID_HIGHEST + 150
ID_TOGGLE_FASTVIEW = ID_TOGGLE_OBJECTS + 1
ID_TOGGLE_SUPPLIED_DATA = ID_TOGGLE_OBJECTS + 2
ID_TOGGLE_COORD_SYSTEM = ID_TOGGLE_OBJECTS + 3
ID_TOGGLE_DISCHARGE = ID_TOGGLE_OBJECTS + 4
ID_TOGGLE_PM = ID_TOGGLE_OBJECTS + 5
ID_TOGGLE_ROCK_BURST = ID_TOGGLE_OBJECTS + 6
ID_TOGGLE_CONTAINER = ID_TOGGLE_OBJECTS + 7
ID_TOGGLE_DEVIATION = ID_TOGGLE_OBJECTS + 8
ID_CHANGE_CREDENTIALS = ID_TOGGLE_OBJECTS + 9
ID_OPEN_TREE = ID_TOGGLE_OBJECTS + 10
ID_OPEN_PM = ID_TOGGLE_OBJECTS + 11
ID_OPEN_ROCK_BURST_TREE = ID_TOGGLE_OBJECTS + 12
ID_OPEN_DISCHARGE = ID_TOGGLE_OBJECTS + 13
ID_OPEN_DOCUMENTS = ID_TOGGLE_OBJECTS + 14
ID_OPEN_CONSOLE = ID_TOGGLE_OBJECTS + 15
ID_OPEN_MAP = ID_TOGGLE_OBJECTS + 16
